### ISSUE TITLE
Broken import resolution on Vitest

### ISSUE THREAD

**Issue by bryanmylee** [solidjs/solid-testing-library#16]
All tests on a brand new SolidJS project with Vitest break due to a `template is not a function` error.

I've created a minimal reproduction here:

https://github.com/bryanmylee/solid-vitest-broken

**Comment by goenning** [comment]
I had the same error and this example fixed it https://github.com/vitest-dev/vitest/tree/main/examples/solid

**Comment by bryanmylee** [comment]
@goenning That works wonderfully, thank you.
