### ISSUE TITLE
Is it still maintained?

### ISSUE THREAD

**Issue by pontakornth** [solidjs/solid-testing-library#17]
The last commit was on February which is seven months ago from the time I wrote this. There are 5 PRs and 1 open issue right now.

**Comment by ryansolid** [comment]
Fair question. The one issue seems like it has no solution currently. The other 4 PRs have crept up on me. Didn't realize it had been 3 months already. I will get back here when I can get a chance but hard to judge the impact of some of these without investigation.

**Comment by atk** [comment]
I took this up from Ryan. Sorry it took so long. New release will be incoming soon.
