### ISSUE TITLE
Executing a test using `render` fails when vitest re-executes

### ISSUE THREAD

**Issue by mathieuprog** [solidjs/solid-testing-library#18]
When running `npm test` with vitest, you don't get the command line back, you may type the Enter key and the test re-executes, or it will re-execute automatically on file changes.

My tests succeed on the first run, but when I press Enter to re-execute, the test fails.

To reproduce:
1. Clone https://github.com/mathieuprog/solid-compose
2. Update solidjs dep as we mentioned here: https://github.com/solidjs/solid/issues/1265 in `/web/dist/dev.js` line 476, as we use `happy-dom`
3. Run `npm test` (tests succeed)
4. Press Enter (test failed)

**Comment by jnlmmln** [comment]
When I use `vitest v0.22.1` it works fine. After updating to v0.23.0 I stops working.

I think it is related to this PR: https://github.com/vitest-dev/vitest/pull/1754

Because setting `isolate: true` in vite.config.ts fixes this issue.

Here is a demo: https://stackblitz.com/edit/solidjs-templates-6usthc?file=vite.config.ts

**Comment by mathieuprog** [comment]
Thank you with that option `isolate: true` it works.

The remaining question is, is it normal that no `HTMLElement` are to be found on second run when isolate option is set to false?
Can the library force to ignore it?
Can we document it?
Is it normal that developers spend literally hours or days on obscure configuration tweaking, instead of coding their actual app functionalities?

**Comment by jnlmmln** [comment]
Regarding the issue that the DOM is empty. When I rerun the tests I get this warning from solidjs:
```typescript
Unrecognized value. Skipped inserting HTMLButtonElement { '$$click': [Function (anonymous)] }
Unrecognized value. Skipped inserting HTMLButtonElement { '$$click': [Function (anonymous)] }
Unrecognized value. Skipped inserting HTMLElement {}
```

Which comes from `solid-js/web/dist/dev.js:446`, and is because of `value instanceof Node` is false  for all reruns. So the "nodes" don't get added to the DOM for reruns.

**Comment by atk** [comment]
This is an error in vitest. The newest version of vitest, if configured correctly, should work. Our testing documentation will be updated soon.
