### ISSUE TITLE
Bug: doesn't work for signal

### ISSUE THREAD

**Issue by zhaoyao91** [solidjs/solid-testing-library#2]
I have a simple test

```tsx
  it("should work for signal", () => {
    const [count, setCount] = createSignal(0);

    const App = () => {
      return <div>{count()}</div>;
    };

    const result = render(() => <App />);

    expect(result.container.innerHTML).toBe("<div>0</div>");

    setCount(1);

    expect(result.container.innerHTML).toBe("<div>1</div>");
  });

```

the second expect does not pass since the result is still `<div>0</div>`

**Comment by ryansolid** [comment]
I suspect this might be related to the version of Solid pulled in. It is possibly the static server version is being pulled in. If using Jest I strongly recommend using [solid-jest](https://github.com/solidjs/solid-jest). Please confirm. I will update the main docs to mention it.

**Comment by zhaoyao91** [comment]
Thanks, it works.
