### ISSUE TITLE
Error: Failed to resolve entry for package "solid-testing-library". 

### ISSUE THREAD

**Issue by HyperGrapher** [solidjs/solid-testing-library#25]
Version 0.4.0 tests are faling with the following error:

Error: Failed to resolve entry for package "solid-testing-library". The package may have incorrect main/module/exports specified in its package.json.

here is the repo: 
https://github.com/HyperGrapher/solid-boilerplate-with-router-and-gsap/actions/runs/3416557288/jobs/5705891534

**Comment by shishkin** [comment]
Building a package from `main` seems to work. @atk could you please release a new version?

**Comment by atk** [comment]
I have already prepared it the day before yesterday, but @ryansolid has to make the release. He was at the jamstack conference, so he couldn't do it in a timely manner.

**Comment by atk** [comment]
0.5.0 is released, which fixes this and adds a few other goodies. Please re-test.

**Comment by HyperGrapher** [comment]
thanks for quick remedy, you people rocks:)

**Comment by atk** [comment]
Thanks for re-testing!
