### ISSUE TITLE
`render`: `wrapper` option should instantiate wrapper before children

### ISSUE THREAD

**Issue by mdickopp** [solidjs/solid-testing-library#27]
Consider the following code from the SolidJS tutorial:

counter.jsx:

```js
import { createSignal, createContext, useContext } from "solid-js";

const CounterContext = createContext();

export function CounterProvider(props) {
  const [count, setCount] = createSignal(props.count || 0),
    counter = [
      count,
      {
        increment() {
          setCount((c) => c + 1);
        },
        decrement() {
          setCount((c) => c - 1);
        },
      },
    ];

  return <CounterContext.Provider value={counter}>{props.children}</CounterContext.Provider>;
}

export function useCounter() {
  return useContext(CounterContext);
}
```

nested.jsx:

```js
import { useCounter } from "./counter";

export default function Nested() {
  const [count, { increment, decrement }] = useCounter();
  return (
    <>
      <div>{count()}</div>
      <button onClick={increment}>+</button>
      <button onClick={decrement}>-</button>
    </>
  );
}
```

When testing `Nested`, it would be beneficial if it could be wrapped in a `CounterProvider` by providing the latter to the `wrapper` option of the `render` function, like this:

```js
import { render } from "solid-testing-library";
import { CounterProvider } from "./counter";
import Nested from "./nested";

it("should contain the counter value", () => {
  const { container } = render(<Nested />, {
    wrapper: (props) => <CounterProvider>{props.children}</CounterProvider>,
  });
  expect(container.querySelector("div").textContent).to.equal("0");
});
```

However, the `useCounter` call fails with the message “TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))”. It seems that `Nested` is instantiated before `CounterProvider`, so that `useCounter` returns `undefined`.

This code works fine:

```js
it("should contain the counter value", () => {
  const { container } = render(() => (
    <CounterProvider>
      <Nested />
    </CounterProvider>
  ));
  expect(container.querySelector("div").textContent).to.equal("0");
});
```

When having many tests, having to wrap `Nested` in `CounterProvider` in each one manually is not economic, so I think it would be beneficial if using the `wrapper` option worked.

**Comment by atk** [comment]
Thanks for reporting this. It should be fixed in https://github.com/solidjs/solid-testing-library/pull/28 - can you verify?

**Comment by mdickopp** [comment]
This fixes the issue for me. Thanks!

**Comment by atk** [comment]
0.5.1 is published with the fix.

**Comment by nmocruz** [comment]
not sure if is broken again, but I same the same issue using 0.5.1
