### ISSUE TITLE
Add wrapper to renderHook

### ISSUE THREAD

**Issue by gabrieldemian** [solidjs/solid-testing-library#31]
Hello! I'm developing solid hooks for a library, and those hooks needs access to a context.

I'm trying to use `renderHook` to test my hooks, the problem is that I need the hook to be inside my provider. Is it possible to add a `wrapper` option to `renderHook` just like we have on `render`?

Thanks in advance.

An example of how that would look like:
```tsx
// test.test.ts
it('is connected', async () => {
  // my custom render hook
   const hookData = myCustomRenderHook(() => hookToBeTested())
   console.log('result -> ', hookData)
})

// other file
// My Provider, children could be passed to ...rest?
const providerWrapper = ({ client = setupClient({ queryClient }), ...rest }: Props) => {
  return (
    <WagmiProvider client={client as any} {...rest} />
  )
}

export function myCustomRenderHook<TResult, TProps extends any[]>(
  hook: (...args: TProps) => TResult,
  options: RenderHookOptions<TProps> | undefined = {},
) {
  // renderHook is the hook from solid-testing-library
  const { owner, result } = renderHook(hook, { wrapper: (props) => providerWrapper(props) })

  runWithOwner(owner!, () => {
    console.log('owner' , owner)
  })

  return {
    result
  }
}

```

**Comment by atk** [comment]
In theory, it's possible. I need to research if it is possible to add a context without creating a JSX tree, which would otherwise be unnecessary overhead.

**Comment by NeOMakinG** [comment]
> In theory, it's possible. I need to research if it is possible to add a context without creating a JSX tree, which would otherwise be unnecessary overhead.

I don't know if it could be useful but here is what I did on our `renderHook` wrapper in order to achieve something, might be wrong or not clean as hell but just sharing: https://github.com/gabrieldemian/wagmi/commit/ced346efc52c67582b6352664349e93db60f12ac

**Comment by NeOMakinG** [comment]
This is a real blocker for the adoption of `solid-testing-library` as it means that we can't test any hooks dependent on a wrapper/provider/context, we need to implement it!

**Comment by gabrieldemian** [comment]
@atk If it is okay to add this, I am available to work to release a PR, while I'm not an expert on Solid, I can be helpful in something in case you need it.

**Comment by atk** [comment]
I will definitely add this, just need to research the best way to do so.

**Comment by gabrieldemian** [comment]
sounds good, thank you so much!

**Comment by atk** [comment]
I just published 0.5.2, which supports wrapper in renderHook. Please test!

**Comment by NeOMakinG** [comment]
> I just published 0.5.2, which supports wrapper in renderHook. Please test!

Just looked at the code, that's smart, I will git it a try later

**Comment by NeOMakinG** [comment]
> I just published 0.5.2, which supports wrapper in renderHook. Please test!

@atk I did the test and it seems to fail somehow: https://github.com/gabrieldemian/wagmi/commit/5a70e016e70ca1fcd786ecf577ae601f51baedfd

Seems like the hook isn't executed within the provider, it doesn't makes sense looking at your code but you might have an idea

**Comment by atk** [comment]
Can you please try again using `"@solidjs/testing-library": "0.5.2"` instead of that local version?

**Comment by NeOMakinG** [comment]
> Can you please try again using `"@solidjs/testing-library": "0.5.2"` instead of that local version?

Same result, because the previous one included your wrapper modifications as it was coming from github with the main branch

**Comment by atk** [comment]
Also, the way you use the wrapper props will not work, because we need to add props to the wrapper to allow to wrap the children with the hook.

**Comment by NeOMakinG** [comment]
> Also, the way you use the wrapper props will not work, because we need to add props to the wrapper to allow to wrap the children with the hook.

Ok, it did the trick, I've to fix some tests but it looks like it works now!

Thanks a lot :)

**Comment by NeOMakinG** [comment]
I confirm every tests run perfectly, you can close the issue, thanks!
