### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'solid-refresh-ctx')

### ISSUE THREAD

**Issue by Jackie1210** [solidjs/solid-testing-library#32]
I just cannot test solid component with `vitest`.

## What i have done
- https://dev.to/mbarzeev/update-testing-a-solidjs-component-using-vitest-1pj9
- https://dev.to/lexlohr/testing-your-solidjs-code-in-vitest-6dh
- https://stackblitz.com/edit/vitest-dev-vitest-2t7qvd?file=package-lock.json&initialPath=__vitest__
- https://github.com/solidjs/solid-testing-library/issues/10

All solutions above didn't work any more

**Comment by dmbdesignpdx** [comment]
I too get this error.

Steps to reproduce:
1. `npm init solid@latest`
2. select `with-vitest`, type `n` for server-side rendering, `y` for typescript
3. `npm i`
4. `npm test`

Versions:
- solid-js@1.6.9
- @solidjs/testing-library@0.5.2
- Node 16.19.0
- NPM 9.2.0

**Comment by qiuzhanghua** [comment]
Me too! sample project as:

https://github.com/qiuzhanghua/solid-sample


It seams occurs when I use "ncu -u" to upgrade all libs.

**Comment by atk** [comment]
Sorry for my late response, I was sick last week. This doesn't seem like an error in solid-testing-library, but rather in the with-vitest template. I'll have a look later regardless.

**Comment by dmbdesignpdx** [comment]
looks like the latest `solid-start` has the updated version of `solid-refresh` and is working.

thanks @atk for getting back and @vchirikov for providing that insight.
