### ISSUE TITLE
vitest mock createResource

### ISSUE THREAD

**Issue by sysmat** [solidjs/solid-testing-library#33]
- is it possible to mock fetch service with result and in render get result of fetch?
- component:

```tsx
const PeopleC: Component = () => {
  const [people] = createResource<Result<Human>>(fetchPeopele);
  const [humans, setHumans] = createSignal<Human[]>();

  createEffect(() => {
    if (people()) {
      setHumans(people()?.results);
    }
  });

  return (
    <div class={styles.People}>

      <span>{people.loading && <Spinner size='28' />}</span>
      <span>{people.error && <Error msg='Napaka pri nalaganju oseb' />}</span>
      <Show
        when={people()}>
        <div class="grid grid-cols-4 gap-2 ">
          <div class="font-semibold text-xs text-left uppercase text-white bg-gray-500">Name</div>
          <div class="font-semiboldtext-xs  text-left uppercase text-white bg-gray-500">height</div>
          <div class="font-semibold text-xs text-left uppercase text-white bg-gray-500">mass</div>
          <div class="font-semibold text-xs text-left uppercase text-white bg-gray-500">Action</div>
        </div>
        <For each={humans()}>
          {(u, i) => <HumanC human={u} index={i()} />}
        </For>
      </Show>
    </div>
  );
};
```
- test:

```tsx
it('should mock some data', async () => {
    const mock = vi.fn().mockImplementation(fetchPeopele);
    mock.mockImplementationOnce(() => Promise.resolve(peoples))
    await render(() => <People />);
    // this below not working
    expect(mock).toHaveBeenCalledTimes(1);
    const name = screen.getByText('Name');
    expect(name).toBeDefined();
  });
```

**Comment by atk** [comment]
You cannot overwrite global imports this way. There are two ways to use mocks:

1. Overwriting of methods using `vi.spy(object, 'methodName'): MockFn`,
2. use `vi.fn()` to create a `MockFn` and find some way to inject it, e.g. as onClick handler

and then use `MockFn.mockImplementation(impl)` to overwrite the behavior.

**Comment by sysmat** [comment]
- I'm more angular just trying some other tools
- test:

```typescript
vi.mock('../shared/service', () => {
  const fetchPeopele = vi.fn()
  const people: Human[] = [
    {
      name: 'tom',
      height: 177,
      mass: 85,
      hair_color: 'black',
      skin_color: 'white'
    },
  ];

  const peoples: Result<Human> = {
    next: '',
    previous: '',
    count: 1,
    results: people
  };

 fetchPeopele.mockResolvedValue(Promise.resolve(peoples));

  return { fetchPeopele }
});

describe('People component', () => {
  afterEach(() => {
    vi.restoreAllMocks()
  })

  it('should mock some data', async () => {
    await render(() => <People />); 
    const name = screen.getByText('Name');
    expect(name).toBeDefined();
  });

});
```

- output from test:

```html
<body>
  <div>
    <div
      class="_People_d50028"
    >
      <span />
      <span />
    </div>
  </div>
</body>
```
- error: Unable to find an element with the text: Name
- so if mock fetchPeopele  works then solidjs should render "tailwind grid", or must be done something to mock `Show        when={people()}`

**Comment by sysmat** [comment]
- PeopleC  is component with list of people, but is like CRUD(I have view component & edit component for Human). 
- that was the only way figure it that work in solidj(create effect for signal which come from resource), because when I edit some human I don't to re fetch all list , because end user may edit two human at once and then save one and the second should be stil in edit mode

**Comment by atk** [comment]
```js
await render(() => <People />)
```

Is that `render` from `@solidjs/testing-library`? Because  that's synchronous and thus, await will do nothing here; resources on the other hand are asynchronous. So you need to wait for `await Promise.resolve()` *after* rendering in order to allow your mock response to resolve.

**Comment by sysmat** [comment]
- Hm, thx for the support but I don't understand what you mean
- I create simple repo: https://stackblitz.com/edit/solidjs-templates-myqh2h?file=src/People.test.tsx

**Comment by atk** [comment]
- You are still using the deprecated `solid-testing-library` instead of `@solidjs/testing-library`.
- `screen.getByText()` is synchronous, so awaiting it does nothing useful, use `queryByText` from the `render` return value instead to be able to run concurrent tests without them influencing each other.

**Comment by sysmat** [comment]
- @atk thx a lot, I didn't realize I was using deprecated lib 
- Maybe in README would be helpful for the new users on how to use this lib(deconstructing, imports, ...)

**Comment by atk** [comment]
We are currently considering moving this project to @testing-library, so we only want to officially document this here after we know whether we will make this move or not, so people don't have to update twice.

I asked Ryan to officially deprecate the old package, but it seems he hasn't yet found the time to do so. I'll ask him again, thanks for notifying me to the issue.

**Comment by sysmat** [comment]
- Hm, this test now pass, but it should not

```typescript
it('should mock some data', async () => {
    const { queryByText } = render(() => <People />);
    expect(await queryByText('BkkaskasaASKSAS')).toBeDefined();
  });
```

- BkkaskasaASKSAS is not in component so it should fail

**Comment by sysmat** [comment]
- I create  Counter component
- I create 2 ways of testing, and by screen working as accepted, but by query it is not working
- repo: https://stackblitz.com/edit/solidjs-templates-myqh2h?file=src/Count.query.test.tsx

**Comment by atk** [comment]
`fireEvent` is not asynchronous either. It is strongly recommended that you use `@testing-library/user-event` instead.

**Comment by sysmat** [comment]
Hm, but when using proper 'Name' it also fail, so mocking not working

**Comment by atk** [comment]
Sorry, my mistake, mixed up queryBy and findBy again. Updated the first example above.

**Comment by sysmat** [comment]
Hm

**Comment by sysmat** [comment]
I'm little bit confused

**Comment by atk** [comment]
One source of your confusion might be the selectors. `getBy` is synchronous and fails if nothing is found. `queryBy` is synchronous, but returns `null` if nothing is found (which is counting as defined, so `.toBeDefined()` will pass even if the element is not available). `findBy` is asynchronous and rejects if no element is found.

**Comment by sysmat** [comment]
- thx for diff `getBy*`, `queryBy*  ` and `findBy*`
- my confusion is about mock data in component

```
1. vi.mock is used because the component is not calling implementation function
2. but component dosen't get values from mockResolvedValue
```

**Comment by atk** [comment]
Ah! `mockResolvedValue` will already make the function return a `Promise`, so either use `mockReturnValue` to return it or remove the `Promise.resolve()` around the value.

**Comment by atk** [comment]
Sorry to ask again, but could you please provide the current code?

**Comment by sysmat** [comment]
https://stackblitz.com/edit/solidjs-templates-myqh2h?file=src%2FPeople.tsx,src%2FPeople.test.tsx

**Comment by sysmat** [comment]
hm, the same code works in stackblitz but not in my computer, strange

**Comment by sysmat** [comment]
@atk thx, my code on computer is more complicated it looks my problem, it works, thx again
