### ISSUE TITLE
Module '"solid-testing-library"' has no exported member 'afterEach'

### ISSUE THREAD

**Issue by captDaylight** [solidjs/solid-testing-library#36]
I'm running through [this testing example](https://docs.solidjs.com/guides/how-to-guides/testing-in-solid/vitest#testing-components) and seeing this error:

<img width="893" alt="Screen Shot 2023-04-27 at 7 20 56 PM" src="https://user-images.githubusercontent.com/700617/235010920-ed234781-9fc1-4a04-8a76-62dd1da71649.png">

**Comment by atk** [comment]
Thank you for raising this issue, but unfortunately, it is in the wrong repo.

`afterEach` is not part of testing-library, but of testing frameworks like mocha or vitest. We export a `cleanup` function that can be called manually in testing frameworks not supporting this global, like e.g. uvu.

The error is in the new solid docs, not in the solid-testing-library. I'll talk to our docs team to have this corrected soon.

**Comment by captDaylight** [comment]
Thank you @atk for the fast response!
