### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by chasm** [solidjs/solid-testing-library#4]
npm i -D solid-testing-library                                                                                                                                                                        12:45:31  ☁  refactor ☂ ✖ ⚡ ✚ ✭
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: op-x@0.0.1
npm ERR! Found: solid-js@0.26.5
npm ERR! node_modules/solid-js
npm ERR!   solid-js@"^0.26.5" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer solid-js@"^1.0.0" from solid-testing-library@0.2.0
npm ERR! node_modules/solid-testing-library
npm ERR!   dev solid-testing-library@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/~/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/~/.npm/_logs/2021-07-09T00_46_22_256Z-debug.log

**Comment by ryansolid** [comment]
Use 0.1.x if you are using a Solid version earlier than 1.0. It looks like your project is on 0.26.5. Either downgrade testing library or update `solid-js` and `babel-preset-solid`.

**Comment by chasm** [comment]
Ah, good to know. I thought I'd upgraded it to 1.0, but I guess not.

**Comment by chasm** [comment]
All good now. Thanks!
