### ISSUE TITLE
Issues using latest vitest results in errors

### ISSUE THREAD

**Issue by cschroeter** [solidjs/solid-testing-library#47]
When updating `vitest` from ` 0.34.2` -> ` 0.34.3` I get a bunch of 

`You appear to have multiple instances of Solid. This can lead to unexpected behavior.`

Send me a PM if you are in the mood ;) @atk

**Comment by floratmin** [comment]
Also with `vitest` `1.2.1`. 
I get the additional error:
```
computations created outside a `createRoot` or `render` will never be disposed
```

**Comment by maxmilton** [comment]
@floratmin see the solution in <https://github.com/solidjs/solid-testing-library/issues/38#issuecomment-1564593881>. You've likely got multiple instances of solid in your tests. Inlining the solid code should should fix your issue.

**Comment by Omikorin** [comment]
We can close it now @atk 🎉

**Comment by atk** [comment]
Fixed
