### ISSUE TITLE
dispose is not a function error in test

### ISSUE THREAD

**Issue by sysmat** [solidjs/solid-testing-library#49]
- node ver: 18.19.0
- dep
```
"@solidjs/testing-library": "^0.8.4",
    "@testing-library/user-event": "^14.5.1",
    "@vitest/coverage-v8": "^0.34.6",
"typescript": "^5.3.2",
    "vite": "^5.0.4",
    "vite-plugin-solid": "2.7.2",
    "vitest": "^0.34.6",
"solid-js": "^1.8.7",
```

**Comment by Omikorin** [comment]
@sysmat this issue is correlated to #48

The only fix for you know is to rollback vitest to 0.34.2 or use Node 18.18.2. In Node 18.19.0 they backported a breaking change in module resolution.

**Comment by joeatwawa** [comment]
Note that this seems to be resolved when using the latest version of vitest (which is 1.2.0 at the time of this writing).

**Comment by atk** [comment]
I moved from throwing an error to issuing a warning. I also updated vite-plugin-solid so it should do most of the required testing config for you (except for globals, coverage, watch, etc.).
