### ISSUE TITLE
vite-plugin-solid should be updated

### ISSUE THREAD

**Issue by sectsect** [solidjs/solid-testing-library#54]
We should update [vite-plugin-solid](https://github.com/solidjs/vite-plugin-solid) to fix [bug](https://github.com/solidjs/solid-refresh/pull/37) on [solid-refresh](https://github.com/solidjs/solid-refresh) .

https://github.com/solidjs/vite-plugin-solid/issues/93

**Comment by atk** [comment]
Not sure how that is related to testing-library. The vite plugin is usually installed in the template, the testing-library is just an extra. I already submitted PRs for all the templates.

**Comment by sectsect** [comment]
@atk 
I'm sorry. It seems my understanding was wrong.
It was unrelated to my problem.
